Webwhatsapp/Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.urls.conf import include

urlpatterns = [
  
    path('admin/', admin.site.urls),
    url(r'', include('Webap.urls')),
   

]

Webwhatsapp/Webap/urls.py
from Webap import views
from django.conf.urls import url
from django.contrib import admin
from django.urls import reverse_lazy
from django.urls import path 

from .views import *

admin.autodiscover()

app_name = 'Webap'

urlpatterns = [
    
    url(r'^$', register, name='signup'),
    url(r'^login/$', login_user, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^add-phone/$', views.phone_add, name='add_phone'),
    url(r'^phone-data/$', PhoneListView.as_view(), name='phone_list'),
    url(r'^phone-delete/$', PhoneDelete.as_view(), name='phone_delete'),
    url(r'^send-message/$', PhoneSelectionSendView.as_view(), name='send_message'),
   
]

Webwhatsapp/Webap/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext, ugettext_lazy as _

# Create your models here.
class User(AbstractUser):
                
    first_name = models.CharField(null=True,blank=True, max_length=15)
    last_name = models.CharField(null=True,blank=True, max_length=15)
    created_time = models.DateTimeField(auto_now_add=True, blank=True)
    admin_verified = models.BooleanField(default=False)
    contact_no = models.CharField(null=True,blank=True, max_length=15)
     
    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')
        db_table = 'User'
        
class PhoneNumber(models.Model):
    
    phone_number =  models.CharField(null=True,blank=True, max_length=15)
    added_by = models.ForeignKey(User,blank=True, null=True, on_delete=models.deletion.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True, blank=True,null=True)
    updated_on = models.DateTimeField(auto_now_add=True, blank=True,null=True)  
    
    class Meta:
        verbose_name = _('Phone Number')
        verbose_name_plural = _('Phone Numbers')
        db_table = 'Phone Number'


        
class Content(models.Model):
    
    phones =  models.ForeignKey(PhoneNumber,blank=True, null=True, on_delete=models.deletion.CASCADE)
    sent_by = models.ForeignKey(User,blank=True, null=True, on_delete=models.deletion.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True, blank=True,null=True)
    updated_on = models.DateTimeField(auto_now_add=True, blank=True,null=True)
    
    
    class Meta:
        verbose_name = _('Content')
        verbose_name_plural = _('Content')
        db_table = 'Content'
        
        
class ContentImages(models.Model):
    
    image = models.FileField(upload_to="images", null=True, blank=True)
    phone_numbers = models.ForeignKey(Content, on_delete=models.CASCADE, related_name="images")
    created_by = models.ForeignKey(User, related_name="content_images", on_delete=models.CASCADE, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = True
        db_table = 'tbl_content_images'
        verbose_name_plural = "content images"        
        
        

Webwhatsapp/Webap/forms.py
import re

from django import forms
from django.contrib.auth.forms import PasswordResetForm
from django.utils.translation import ugettext_lazy as _

from .models import *

regex = re.compile('[@_!#$%^&*()<>?/\|}{~:]')


class CreateUserForm(forms.Form):
    email = forms.EmailField(
        label=_("Email"), widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'input100 form-control'}),
        required=True)

    first_name = forms.CharField(label=_("First name"), max_length=30,
                                 widget=forms.TextInput(
                                     attrs={'placeholder': 'First name', 'class': 'input100 form-control'}),
                                 required=True
                                 )
    last_name = forms.CharField(label=_("Last name"), max_length=30,
                                widget=forms.TextInput(
                                    attrs={'placeholder': 'Last name', 'class': 'input100 form-control'}), required=True
                                )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'input100 form-control'}), required=True
    )

    def clean_first_name(self):
        if (regex.search(self.cleaned_data["first_name"]) != None):
            raise forms.ValidationError(
                _("First Name cannot contain special characters."))
        else:
            return self.cleaned_data["first_name"]

    def clean_last_name(self):
        if (regex.search(self.cleaned_data["last_name"]) != None):
            raise forms.ValidationError(
                _("Last Name cannot contain special characters."))
        else:
            return self.cleaned_data["last_name"]

    def clean_email(self):
        value = self.cleaned_data["email"]
        qs = User.objects.filter(email__iexact=value)
        if not qs.exists():
            return value
        raise forms.ValidationError(
            _("A user is registered with this email address."))


class PhoneForm(forms.Form):
    class Meta:
        model = PhoneNumber
        fields = ('phone_number',)

Webwhatsapp/Webap/views.py
from datetime import timedelta
import datetime
from django.contrib.auth import get_user_model

from django.contrib import auth
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View
from django.views.generic.edit import CreateView
from .forms import *
import pywhatkit
import pytz
from django.conf import settings
from selenium import webdriver
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time
import sys
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import datetime
import time
import webbrowser
import pyautogui as gui
import os
# try:
import autoit
# except ModuleNotFoundError:
#     pass

import schedule
# Importing traceback to catch xml button not found errors in the future
import traceback
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.options import Options


import time
import datetime
import os
import argparse
import platform
# import openpyxl as excel

# Create your views here.
User = get_user_model()


class UserCreate(CreateView):
    model = User
    form = CreateUserForm
    fields = ["first_name", "last_name", "email", "password", "contact_no"]
    template_name = "signup.html"

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')


User = get_user_model()


@csrf_exempt
def login_user(request, template_name=None, extra_context=None):
    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.admin_verified == True:
                login(request, user)
                return redirect('Webap:add_phone')

            else:
                messages.error(
                    request, 'Please ask admin to verify your account!If already verified please check your email or password!')
                return redirect('Webap:login')

    return render(request, 'login.html', {})


def register(request):
    if request.method == 'POST':

        form = CreateUserForm(request.POST)

        if form.is_valid():
            if not request.POST.get('email', None) or not request.POST.get('contact_no', None):
                messages.error(
                    request, 'Registration failed! Please enter details.')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

            if User.objects.filter(email=request.POST.get('email', None)):
                messages.error(
                    request, 'User already exist with this email id.')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

            if User.objects.filter(contact_no=request.POST.get('contact_no', None)):
                messages.error(
                    request, 'User already exist with this mobile no.')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

            user = User.objects.create(
                email=request.POST.get('email'),
                first_name=request.POST.get('first_name'),
                last_name=request.POST.get('last_name'),
                username=request.POST.get('email'),
                password=request.POST.get('password'),
                contact_no=request.POST.get('contact_no'),
                admin_verified=False
            )

            user.set_password(user.password)
            user.save()
            messages.info(
                request, 'Signed Up Successfully!Please wait for admin to verify your account')
            return redirect('Webap:login')
        else:
            return render(request, 'signup.html', {'form': form}, status=201)

    form = CreateUserForm()
    return render(request, 'signup.html', {'form': form})


def logout(request):
    auth.logout(request)

    return redirect('Webap:login')


def phone_add(request):

    if request.method == 'POST':
        p = PhoneNumber.objects.create(
            phone_number=request.POST.get('phone_number'),
            added_by=request.user,

        )

        messages.info(request, 'Phone number added successfully!')
        return redirect('Webap:phone_list')
    else:
        return render(request, 'add_phone.html')


class PhoneListView(View):

    def get(self, request, *args, **kwargs):

        products = PhoneNumber.objects.filter(
            added_by=request.user).order_by("created_on")

        products = products

        return render(request, "phone_data_list.html", {
            "products": products,

        })


class PhoneDelete(View):

    def get(self, request, *args, **kwargs):
        product = PhoneNumber.objects.filter(
            id=request.GET.get("phone_id", None))
        if product:
            product.delete()
            messages.info(request, 'Phone number deleted successfully!')
        return redirect(request.META.get("HTTP_REFERER"))


if platform.system() == 'Darwin':
    # MACOS Path
    chrome_default_path = os.getcwd() + '/driver/chromedriver'
else:
    # Windows Path
    chrome_default_path = os.getcwd() + '/driver/chromedriver.exe'

# parser = argparse.ArgumentParser(description='PyWhatsapp Guide')
# parser.add_argument('--chrome_driver_path', action='store', type=str, default=chrome_default_path,
#                     help='chromedriver executable path (MAC and Windows path would be different)')
# parser.add_argument('--message', action='store', type=str,
#                     default='', help='Enter the msg you want to send')
# parser.add_argument('--remove_cache', action='store', type=str, default='False',
#                     help='Remove Cache | Scan QR again or Not')
# parser.add_argument('--import_contact', action='store', type=str, default='False',
#                     help='Import contacts.txt or not (True/False)')
# parser.add_argument('--enable_headless', action='store', type=str, default='False',
#                     help='Enable Headless Driver (True/False)')
# args = parser.parse_args()

# if args.remove_cache == 'True':
#     os.system('rm -rf User_Data/*')
browser = None
Contact = None
# message = None if args.message == '' else args.message
Link = "https://web.whatsapp.com/"
wait = None
choice = None
docChoice = None
doc_filename = None
unsaved_Contacts = None


def input_contacts():
    global Contact, unsaved_Contacts
    # List of Contacts
    Contact = []
    unsaved_Contacts = []
    while True:
        # Enter your choice 1 or 2
        print("PLEASE CHOOSE ONE OF THE OPTIONS:\n")
        print("1.Message to Saved Contact number")
        print("2.Message to Unsaved Contact number\n")
        x = int(input("Enter your choice(1 or 2):\n"))
        print()
        if x == 1:
            n = int(input('Enter number of Contacts to add(count)->'))
            print()
            for i in range(0, n):
                inp = str(input("Enter contact name(text)->"))
                inp = '"' + inp + '"'
                # print (inp)
                Contact.append(inp)
        elif x == 2:
            n = int(input('Enter number of unsaved Contacts to add(count)->'))
            print()
            for i in range(0, n):
                # Example use: 919899123456, Don't use: +919899123456
                # Reference : https://faq.whatsapp.com/en/android/26000030/
                inp = str(input(
                    "Enter unsaved contact number with country code(interger):\n\nValid input: 91943xxxxx12\nInvalid input: +91943xxxxx12\n\n"))
                # print (inp)
                unsaved_Contacts.append(inp)

        choi = input("Do you want to add more contacts(y/n)->")
        if choi == "n":
            break

    if len(Contact) != 0:
        print("\nSaved contacts entered list->", Contact)
    if len(unsaved_Contacts) != 0:
        print("Unsaved numbers entered list->", unsaved_Contacts)
    input("\nPress ENTER to continue...")


def input_message():
    global message
    # Enter your Good Morning Msg
    print(
        "Enter the message and use the symbol '~' to end the message:\nFor example: Hi, this is a test message~\n\nYour message: ")
    message = ['hello']
    done = False

    while not done:
        temp = input()
        if len(temp) != 0 and temp[-1] == "~":
            done = True
            message.append(temp[:-1])
        else:
            message.append(temp)
    message = "\n".join(message)
    print(message)


def whatsapp_login(chrome_path, headless):
    global wait, browser, Link
    chrome_options = Options()
    # chrome_options.add_argument('--user-data-dir=./User_Data')
    # if headless == 'True':
    #     chrome_options.add_argument('--headless')
    browser = webdriver.Chrome(
        executable_path=chrome_path, options=chrome_options)
    wait = WebDriverWait(browser, 600)
    browser.get(Link)
    browser.maximize_window()
    print("QR scanned")


def send_message(target):
    global message, wait, browser
    try:
        x_arg = '//span[contains(@title,' + target + ')]'
        ct = 0
        while ct != 5:
            try:

Webwhatsapp/Webap/templates/add_phone.html
<!DOCTYPE Html>
<html>
	<head>
		<meta charset="utf-8">
		 <meta name="format-detection" content="telephone=no">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Web Whatsapp</title>
		<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="/static/css/style.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="css/font-awesome.css" type="text/css" />
		<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet"> 
		<!--[if lt IE 9]>
			<script src="js/html5shiv.js"></script>
			<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
			<script src="js/respond.js"></script>
		<![endif]-->
	</head>
<body>
	
	<!--header start-->	
	<header class="header header_inner">
		<div class="container">
			<nav class="navbar">
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>                        
			      </button>
			    </div>
			    <div class="collapse navbar-collapse pull-right right_nav_bar" id="myNavbar">
			      <ul class="nav navbar-nav nav_list">
			      <li ><a href="{% url 'Webap:phone_list' %}" >Phone list</a></li>
			      <li ><a href="{% url 'Webap:send_message' %}" >Send Message</a></li>
			      
			      {% if request.user %}
			      <li ><a href="{% url 'Webap:logout' %}" >Logout</a></li>
			      {% endif %}
			      
			        
			      </ul>
			        
			      </ul>
			    </div>
			</nav>
		</div>
	</header>
	<!--header end-->

	<!--banner start-->	
	<section class="banner">
		<div class="container">
			<div class="white_box">
				<div class="form_title">
					<h2>New Phone Number</h2>
					<p>Enter your information below</p>
				</div>
				{% if messages %}
				<ul class="messages">
				    {% for message in messages %}
				     <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
				        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
				        {{ message }}
				     </div>
				    {% endfor %}
				</ul>
				{% endif %}
				<form action="{% url 'Webap:add_phone' %}" class="custom_form" method="POST">
				{% csrf_token %}
				
				  <div class="form-group">
				    <label for="name">Phone Number</label>
				    <input type="text" name="phone_number" class="form-control" placeholder="Enter Name">
				  </div>
				 


				  <input type="submit" class="solid_btn yellow_btn" value="Submit"/>

				</form> 
			</div>
		</div>
		
		<div class="copy_right">
			<p>© 2020  All rights reserved.</p>
		</div>
	</section>
	<!--banner end-->

	
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  
</body>
</html>

Webwhatsapp/Webap/templates/phone-selection.html
<!DOCTYPE Html>
<html>
	<head>
		<meta charset="utf-8">
		 <meta name="format-detection" content="telephone=no">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Web Whatsapp</title>
		<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="/static/css/style.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="css/font-awesome.css" type="text/css" />
		<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet"> 
		<!--[if lt IE 9]>
			<script src="js/html5shiv.js"></script>
			<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
			<script src="js/respond.js"></script>
		<![endif]-->
		<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
	</head>
<body>
	
	<!--header start-->	
	<header class="header header_inner">
		<div class="container">
			<nav class="navbar">
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>                        
			      </button>
			    </div>
			    <div class="collapse navbar-collapse pull-right right_nav_bar" id="myNavbar">
			      <ul class="nav navbar-nav nav_list">
			      <li ><a href="{% url 'Webap:add_phone' %}" >Add New</a></li>
			      {% if request.user %}
			      <li ><a href="{% url 'Webap:logout' %}" >Logout</a></li>
			      {% endif %}
			      
			        
			      </ul>
			    </div>
			</nav>
		</div>
		{% if messages %}
					<ul class="messages">
					    {% for message in messages %}
					    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
					        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
					        {{ message }}
					    </li>
					    {% endfor %}
					</ul>
					{% endif %}
	</header>
	<!--header end-->

	<!--banner start-->	
	<section class="banner">
		<div class="container">
		 <form action="{% url 'Webap:send_message'%}" class="product-selection"
                                  method="post">
                                  {% csrf_token %}
			<div class="row">
				<h2>Phone List</h2>
                      
						<table>
						  <tr>
						  
						    <th>Phone Number</th>
						    <th>Created on</th>
						    <th>Updated On</th>
						     
						  </tr>
						   {% for data in products %}
						  <tr>
						  <td>
                             <div class="form-check chk-box">
                                 <input class="form-check-input" id="exampleCheck1"
                                        name="selected_products" type="checkbox"
                                        value="{{data.id}}">
                             </div>
                                            
                                 	</td>
						    <td>{{data.phone_number}}</td>
						    <td>{{data.created_on}}</td>
						    <td>{{data.updated_on}}</td>
						  <td><a class="btn btn-default" href="{% url 'Webap:phone_delete' %}?phone_id={{data.id}}"><span class="glyphicon glyphicon-trash"></span></a></td>
						    
						  </tr>
						{% endfor %}		
						  
						</table>
									
					 <div class="form-group">
				    <label for="name">Message</label>
				    <input type="text" name="message" class="form-control" placeholder="Enter Name">
				  </div>
				  
				   <div class="form-group">
				    <label for="name">Image</label>
				    <input type="file" name="image" class="form-control" placeholder="Upload field">
				  </div>

				<div class="buton-save">
                 <button class="btn btn-success btn-lg float-right" href="#2" type="submit">Send
                 </button>
                                </div>
			</div>	
			</form>
		</div>
		 
		<div class="copy_right">
			<p>© 2020  All rights reserved.</p>
		</div>
	</section>
	<!--banner end-->

	
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
 

{% if l.has_other_pages %}
  <ul class="pagination">
    {% if l.has_previous %}
      <li><a href="?page={{ l.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in l.paginator.page_range %}
      {% if l.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}
      <li><a href="?page={{ l.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %} 
</body>
</html>

Webwhatsapp/Webap/templates/phone_data_list.html
<!DOCTYPE Html>
<html>
	<head>
		<meta charset="utf-8">
		 <meta name="format-detection" content="telephone=no">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Web Whatsapp</title>
		<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="/static/css/style.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="css/font-awesome.css" type="text/css" />
		<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet"> 
		<!--[if lt IE 9]>
			<script src="js/html5shiv.js"></script>
			<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
			<script src="js/respond.js"></script>
		<![endif]-->
		<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
	</head>
<body>
	
	<!--header start-->	
	<header class="header header_inner">
		<div class="container">
			<nav class="navbar">
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>                        
			      </button>
			    </div>
			    <div class="collapse navbar-collapse pull-right right_nav_bar" id="myNavbar">
			      <ul class="nav navbar-nav nav_list">
			      <li ><a href="{% url 'Webap:add_phone' %}" >Add New</a></li>
			      <li ><a href="{% url 'Webap:send_message' %}" >Send Message</a></li>
			      {% if request.user %}
			      <li ><a href="{% url 'Webap:logout' %}" >Logout</a></li>
			      {% endif %}
			      
			        
			      </ul>
			    </div>
			</nav>
		</div>
		{% if messages %}
					<ul class="messages">
					    {% for message in messages %}
					    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
					        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
					        {{ message }}
					    </li>
					    {% endfor %}
					</ul>
					{% endif %}
	</header>
	<!--header end-->

	<!--banner start-->	
	<section class="banner">
		<div class="container">
		
			<div class="row">
				<h2>Phone List</h2>
                      
						<table>
						  <tr>
						    <th>Phone Number</th>
						    <th>Created on</th>
						    <th>Updated On</th>
						  </tr>
						   {% for data in products %}
						  <tr>
						    <td>{{data.phone_number}}</td>
						    <td>{{data.created_on}}</td>
						    <td>{{data.updated_on}}</td>
						  <td><a class="btn btn-default" href="{% url 'Webap:phone_delete' %}?phone_id={{data.id}}"><span class="glyphicon glyphicon-trash"></span></a></td>
						    
						  </tr>
						{% endfor %}		
						  
						</table>
									
					

				
			</div>	
		</div>
		
		<div class="copy_right">
			<p>© 2020  All rights reserved.</p>
		</div>
	</section>
	<!--banner end-->

	
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
 

{% if l.has_other_pages %}
  <ul class="pagination">
    {% if l.has_previous %}
      <li><a href="?page={{ l.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in l.paginator.page_range %}
      {% if l.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}
      <li><a href="?page={{ l.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %} 
</body>
</html>